// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwoRskcqNlkJ9TToz8WWan7JdHsbkFRo',
    appId: '1:857197209708:web:96648c45bba6441351d049',
    messagingSenderId: '857197209708',
    projectId: 'an-cu-connect-d336d',
    authDomain: 'an-cu-connect-d336d.firebaseapp.com',
    storageBucket: 'an-cu-connect-d336d.appspot.com',
    measurementId: 'G-6L8ER0FY6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruuxx7yUruY5rcl8JzTLnH7BceIEDuRs',
    appId: '1:857197209708:android:607b4b1d3dabbd3f51d049',
    messagingSenderId: '857197209708',
    projectId: 'an-cu-connect-d336d',
    storageBucket: 'an-cu-connect-d336d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwCtaEsreeJxo0fxB2HCgjpPMeHsdUkQ',
    appId: '1:857197209708:ios:b417207997be5f1351d049',
    messagingSenderId: '857197209708',
    projectId: 'an-cu-connect-d336d',
    storageBucket: 'an-cu-connect-d336d.appspot.com',
    iosBundleId: 'com.example.anCu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwCtaEsreeJxo0fxB2HCgjpPMeHsdUkQ',
    appId: '1:857197209708:ios:b417207997be5f1351d049',
    messagingSenderId: '857197209708',
    projectId: 'an-cu-connect-d336d',
    storageBucket: 'an-cu-connect-d336d.appspot.com',
    iosBundleId: 'com.example.anCu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiwoRskcqNlkJ9TToz8WWan7JdHsbkFRo',
    appId: '1:857197209708:web:91d8683e5b0ca8c051d049',
    messagingSenderId: '857197209708',
    projectId: 'an-cu-connect-d336d',
    authDomain: 'an-cu-connect-d336d.firebaseapp.com',
    storageBucket: 'an-cu-connect-d336d.appspot.com',
    measurementId: 'G-S8ML617F1H',
  );
}
