// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQL5nYgXkfyHePSHMhMFK6L0yVgk8wEnE',
    appId: '1:640994626485:web:56afd8248f7ea63582e7fc',
    messagingSenderId: '640994626485',
    projectId: 'an-cu-connect',
    authDomain: 'an-cu-connect.firebaseapp.com',
    storageBucket: 'an-cu-connect.appspot.com',
    measurementId: 'G-KV544FVKTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8qrR4LqiFJOfhnTV0MEUyWxEfh0FqBb0',
    appId: '1:640994626485:android:fdc4abab59749fe082e7fc',
    messagingSenderId: '640994626485',
    projectId: 'an-cu-connect',
    storageBucket: 'an-cu-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApeOHUMpzIUv7HomoGMgLjIdAimLVChoI',
    appId: '1:640994626485:ios:d46d251f9a4f1b4c82e7fc',
    messagingSenderId: '640994626485',
    projectId: 'an-cu-connect',
    storageBucket: 'an-cu-connect.appspot.com',
    iosBundleId: 'com.example.anCu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApeOHUMpzIUv7HomoGMgLjIdAimLVChoI',
    appId: '1:640994626485:ios:d46d251f9a4f1b4c82e7fc',
    messagingSenderId: '640994626485',
    projectId: 'an-cu-connect',
    storageBucket: 'an-cu-connect.appspot.com',
    iosBundleId: 'com.example.anCu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQL5nYgXkfyHePSHMhMFK6L0yVgk8wEnE',
    appId: '1:640994626485:web:91581592253d07d882e7fc',
    messagingSenderId: '640994626485',
    projectId: 'an-cu-connect',
    authDomain: 'an-cu-connect.firebaseapp.com',
    storageBucket: 'an-cu-connect.appspot.com',
    measurementId: 'G-4EXMTXS31H',
  );

}